#!/bin/sh

export CONF_DIR=~/.dotfiles
export MPORTS_DIR=/opt/local/bin
export SCRIPT_DIR=~/.scripts

export DIRCOLORS=gdircolors
export EMACS='/opt/local/bin/emacs'
export LS=gls
export XARGS=gxargs

# prefer macports stuff
PATH=$MPORTS_DIR:$PATH
. $CONF_DIR/bash/bashrc-base

PATH=$PATH:$HOME/.rvm/bin
source ~/.rvm/scripts/rvm
source $rvm_path/scripts/completion
