#!/bin/sh

export CONF_DIR=~/.dotfiles

export DIRCOLORS=gdircolors
export EMACS="emacsclient -a '' -t"
export LS=gls
export XARGS=gxargs

# prefer macports stuff
PATH=/opt/local/bin/:$PATH
. $CONF_DIR/bash/bashrc-base
