# local settings
. ~/.bashrc-local-pre

PATH=~/scripts:~/scripts/local:$PATH:/opt/local/bin/

export PS1="\w$ "
export EDITOR=emacs
export HISTSIZE=50000

# update bash history after each command
export PROMPT_COMMAND="history -a"

alias e='emacs'
if [ -n "$LS" ]
then
    alias ls='$LS --color=auto'
else
    alias ls='ls --color=auto'
fi
alias l='ls'

source $CONF_DIR/git/git-completion.bash
alias gadd='git add'
alias gbranch='git branch'
alias gcheck='git check'
alias gcommit='git commit'
alias gdiff='git diff'
alias gfetch='git fetch'
alias gllog='git llog'
alias gmerge='git merge'
alias gpull='git pull'
alias gpush='git push'
alias grebase='git rebase'
alias greset='git reset'
alias gshow='git show'
alias gstash='git stash'
alias gstatus='git status'

alias h='ssh hilbert.mtv.corp.google.com'

eval `dircolors $CONF_DIR/solarized/dircolors.256dark`

# local overrides
. ~/.bashrc-local-post
