# local settings
. ~/.bashrc-local-pre

SCRIPT_PATH=~/scripts:~/scripts/kiki:~/scripts/local
PATH=$SCRIPT_PATH:$PATH:/opt/local/bin/

export PS1="\w$ "
export EDITOR=emacs
export HISTSIZE=50000

# update bash history after each command
export PROMPT_COMMAND="history -a"

alias e='emacs'
if [ -n "$LS" ]
then
    alias ls='$LS --color=auto'
else
    alias ls='ls --color=auto'
fi
alias l='ls'

source $CONF_DIR/git/git-aliases.bash
source $CONF_DIR/git/git-completion.bash

source ~/scripts/kiki/register-kcd

alias h='ssh hilbert.mtv.corp.google.com'

if [ -z "$DIRCOLORS" ]
then
   DIRCOLORS=dircolors
fi

eval `$DIRCOLORS $CONF_DIR/solarized/dircolors.256dark`

# local overrides
. ~/.bashrc-local-post
